spring.application.name=canals

logging.level.root =WARN

# >>>>>I KNOW THIS MUST BE IN A .ENV, BUT THIS IS JUST FOR THE TEST<<<<<

spring.datasource.url=jdbc:mysql://localhost:3306/canalsdb?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false